version: '2'
services:
  app:
    build: .
    image: this_is_a_test
    environment:
      NODE_ENV: development
    tty: true
    ports:
      - '4000:80'
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.2.5
